[theme]
base = "light"
primaryColor = "#4F46E5"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F3F4F8"
textColor = "#1F2937"
 
[server]
maxUploadSize = 8
 
[browser]
gatherUsageStats = false
 
